name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      run_non_integration:
        description: 'Run non-integration tests'
        required: true
        default: true
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python version check
        run: pytest -v tests/test_python_version.py
      - name: Run non-integration tests
        if: github.event_name == 'push' || github.event.inputs.run_non_integration
        run: make test
      - name: Run integration tests
        run: pytest -v -m "integration"

